---
title: Cook Responses
params: 
  inputDir: "gathered/"
  thisDir:  "cook/"
  outputDir: "cooked/"
  fileStem: "responses"
---

```{r include = FALSE}
knitr::opts_knit$set(root.dir = normalizePath('../'))

knitr::opts_chunk$set(
  echo = TRUE
  , warning = TRUE
  , message = TRUE
  , error = TRUE
)

library(tidyverse)
```

# Import

```{r }
tbl_col_names <- read_csv(
  file.path("gathered", "technology_survey_responses.csv")
  , n_max = 2
  , col_names = FALSE
  , na = " "
)

col_names <- tbl_col_names %>% 
  apply(2, paste, collapse = " ") %>% 
  unname() %>%
  str_replace_all("NA", "") %>% 
  str_replace_all(" ", "_") %>% 
  str_replace_all("-", "_") %>% 
  str_remove_all("^_") %>% 
  str_remove_all("response") %>% 
  str_remove_all("[,/?]") %>% 
  str_remove_all("(please_specify)") %>% 
  str_remove_all("\\)$") %>%
  str_remove_all("\\($") %>%
  str_remove_all("_$") %>% 
  str_replace_all("__", "_") %>% 
  str_remove_all("_Response") %>% 
  str_remove_all("Which_of_the_following_general_analytic_techniques_do_you_use_regularly_") %>% 
  tolower()

col_names[10] <- "how_often_use_R"
col_names[11] <- "how_often_use_Excel"
col_names[12] <- "how_often_use_GoogleSheets"
col_names[13] <- "how_often_use_SAS"
col_names[14] <- "how_often_use_Python"
col_names[15] <- "how_often_use_Tableau"
col_names[16] <- "how_often_use_MATLAB"
col_names[17] <- "how_often_use_PowerBI"
col_names[18] <- "how_often_use_SQL"

col_names[19] <- "how_proficient_R"
col_names[20] <- "how_proficient_Excel"
col_names[21] <- "how_proficient_GoogleSheets"
col_names[22] <- "how_proficient_SAS"
col_names[23] <- "how_proficient_Python"
col_names[24] <- "how_proficient_Tableau"
col_names[25] <- "how_proficient_MATLAB"
col_names[26] <- "how_proficient_PowerBI"
col_names[27] <- "how_proficient_SQL"

col_names[28] <- "suited_ratemaking_R"
col_names[29] <- "suited_reserving_R"
col_names[30] <- "suited_capital_modeling_R"

col_names[31] <- "suited_ratemaking_Excel"
col_names[32] <- "suited_reserving_Excel"
col_names[33] <- "suited_capital_modeling_Excel"

col_names[34] <- "suited_ratemaking_GoogleSheets"
col_names[35] <- "suited_reserving_GoogleSheets"
col_names[36] <- "suited_capital_modeling_GoogleSheets"

col_names[37] <- "suited_ratemaking_SAS"
col_names[38] <- "suited_reserving_SAS"
col_names[39] <- "suited_capital_modeling_SAS"

col_names[40] <- "suited_ratemaking_Python"
col_names[41] <- "suited_reserving_Python"
col_names[42] <- "suited_capital_modeling_Python"

col_names[43] <- "suited_ratemaking_Tableau"
col_names[44] <- "suited_reserving_Tableau"
col_names[45] <- "suited_capital_modeling_Tableau"

col_names[46] <- "suited_ratemaking_MATLAB"
col_names[47] <- "suited_reserving_MATLAB"
col_names[48] <- "suited_capital_modeling_MATLAB"

col_names[49] <- "suited_ratemaking_PowerBI"
col_names[50] <- "suited_reserving_PowerBI"
col_names[51] <- "suited_capital_modeling_PowerBI"

col_names[52] <- "suited_ratemaking_SQL"
col_names[53] <- "suited_reserving_SQL"
col_names[54] <- "suited_capital_modeling_SQL"

col_names[55] <- "what_other_tools_should_be_added"

col_names[56] <- "increase_proficiency_R"
col_names[57] <- "increase_proficiency_Excel"
col_names[58] <- "increase_proficiency_GoogleSheets"
col_names[59] <- "increase_proficiency_SAS"
col_names[60] <- "increase_proficiency_Python"
col_names[61] <- "increase_proficiency_Tableau"
col_names[62] <- "increase_proficiency_MATLAB"
col_names[63] <- "increase_proficiency_PowerBI"
col_names[64] <- "increase_proficiency_SQL"
col_names[65] <- "increase_proficiency_other"

col_names[66] <- "learning_barriers_inadequate_staff"
col_names[67] <- "learning_barriers_lack_of_managment_support"
col_names[68] <- "learning_barriers_lack_of_it_support"
col_names[69] <- "learning_barriers_financial_cost"
col_names[70] <- "learning_barriers_not_enough_time"
col_names[71] <- "learning_barriers_no_perceived_benefit"
col_names[72] <- "learning_barriers_other"

col_names[73] <- "implementation_barriers_inadequate_staff"
col_names[74] <- "implementation_barriers_lack_of_managment_support"
col_names[75] <- "implementation_barriers_lack_of_it_support"
col_names[76] <- "implementation_barriers_financial_cost"
col_names[77] <- "implementation_barriers_not_enough_time"
col_names[78] <- "implementation_barriers_no_perceived_benefit"
col_names[79] <- "implementation_barriers_other"

col_names[80] <- "linear_models"

col_names[84] <- "bayesian"

col_names[86] <- "time_series"

col_names[89] <- "tree_based_methods"
col_names[90] <- "unsupervised_learning"

col_names[80:91] <- paste0("techniques_", col_names[80:91])

col_names[92] <- "additional_comments"
col_names[96] <- "located_other"
col_names[98] <- "type_of_company_other"
col_names[99] <- "actuaries_at_my_organization"
col_names[100] <- "years_of_experience"

tbl_responses <- read_csv(
  file.path("gathered", "technology_survey_responses.csv")
  , skip = 2
  , col_names = col_names
)
```

# Wrangle

```{r }
tbl_responses <- tbl_responses %>% 
  select(-ip_address, -email_address, -first_name, -last_name, -custom_data_1)

tbl_responses <- tbl_responses %>% 
  mutate_at(vars(start_date, end_date), lubridate::mdy_hms) %>% 
  mutate(
    time_to_complete = end_date - start_date
    , type_of_company_other = tolower(type_of_company_other)
  )

na_to_bool <- function(x) {
  !is.na(x)
}

techniques_col <- names(tbl_responses) %>% 
  str_subset("techniques") %>% 
  str_subset("other", negate = TRUE)

barriers_col <- names(tbl_responses) %>% 
  str_subset("barriers") %>% 
  str_subset("other", negate = TRUE)

proficiency_col <- names(tbl_responses) %>% 
  str_subset("proficiency") %>% 
  str_subset("other", negate = TRUE)

tbl_responses <- tbl_responses %>% 
  mutate_at(c(techniques_col, barriers_col, proficiency_col), na_to_bool)
```

## Factors with levels

```{r }
f_usage <- c(
  'Not at all'
  , 'Less than once a month'
  , 'About once a month'
  , 'About once a week'
  , 'At least once a day'
) %>% 
  as_factor()

f_how_proficient <- c(
  "Not at all"
  , "Basic stuff"
  , "Intermediate"
  , "Advanced"
  , "Expert"
) %>% 
  as_factor()

f_suited <- c(
  "Unsure"
  , "Not at all"
  , "Somewhat"
  , "Very much so"
) %>% 
  as_factor()

f_designation <- c(
  'None yet'
  , 'ACAS'
  , 'FCAS'
) %>% 
  as_factor()

f_age <- c(
  'Prefer not to say'
  , 'Up to 30 years old'
  , '31-40 years old'
  , '41-50 years old'
  , '51-60 years old'
  , '61 or older'
) %>% 
  as_factor()

f_actuaries_at <- c(
  "1-5"
  , "6-10"
  , "11-25"
  , "26-50"
  , "51-200"
  , "200+"
) %>% 
  as_factor()

f_years_of_experience <- c(
  "Less than 5"
  , "Between 5 and 10"
  , "Between 10 and 15"
  , "Between 15 and 20"
  , "More than 20"
) %>% 
  as_factor()

relevel_factors <- function(x, new_levels){
  x %>% 
    factor(levels = new_levels)
}

often_use_cols <- names(tbl_responses) %>% 
  str_subset("how_often_use_")

how_proficient_cols <- names(tbl_responses) %>% 
  str_subset("how_proficient")

suited_cols <- names(tbl_responses) %>% 
  str_subset("suited_")

tbl_responses <- tbl_responses %>%
  mutate_at(often_use_cols, relevel_factors, new_levels = f_usage) %>% 
  mutate_at(how_proficient_cols, relevel_factors, new_levels = f_how_proficient) %>% 
  mutate_at(suited_cols, relevel_factors, new_levels = f_suited)


tbl_responses <- tbl_responses %>% 
  mutate(
    designation = factor(designation, levels = f_designation)
    , age = factor(age, f_age)
    , actuaries_at_my_organization = factor(actuaries_at_my_organization, f_actuaries_at)
    , years_of_experience = factor(years_of_experience, levels = f_years_of_experience)
  )
```

# Demographic

```{r}
tbl_demographic <- tbl_responses %>% 
  select(
    respondent_id, designation, age, where_are_you_located
    , what_type_of_company_do_you_work_for, actuaries_at_my_organization
    , years_of_experience) %>% 
  mutate(
    what_type_of_company_do_you_work_for = what_type_of_company_do_you_work_for %>% 
      str_remove_all(" \\(please specify\\)") %>% 
      str_replace("Firm", "firm")
  )
```

# Melted tools

```{r }
str_fix_tools <- function(str_in) {
  str_in %>% 
    str_replace("PowerBI", "Power BI") %>% 
    str_replace("GoogleSheets", "Google Sheets")
}

tbl_usage <- tbl_responses %>% 
  select(respondent_id, starts_with("how_often")) %>% 
  pivot_longer(cols = -respondent_id, names_to = 'tool', values_to = 'usage_frequency') %>% 
  mutate(
    tool = str_remove(tool, 'how_often_use_') %>% 
      str_fix_tools()
    , uses = usage_frequency != 'Not at all'
    , ge_week = usage_frequency %in% c('About once a week', 'At least once a day')
    , scripter = (tool %in% c('R', 'Python', 'MATLAB', 'SAS')) &
      (ge_week)
  )

tbl_proficiency <- tbl_responses %>% 
  select(respondent_id, starts_with("how_proficient")) %>% 
  pivot_longer(cols = -respondent_id, names_to = 'tool', values_to = 'proficiency') %>% 
  mutate(
    tool = str_remove(tool, 'how_proficient_') %>% 
      str_fix_tools()
  )

tbl_increase_proficiency <- tbl_responses %>% 
  select(respondent_id, starts_with('increase_proficiency')) %>% 
  select(-increase_proficiency_other) %>% 
  pivot_longer(
    cols = starts_with('increase_proficiency')
    , names_to = 'tool'
    , values_to = 'increase_proficiency') %>% 
  mutate(
    tool = tool %>% 
      str_remove('increase_proficiency_') %>% 
      str_fix_tools()
  ) %>% 
  inner_join(tbl_demographic, by = 'respondent_id')

tbl_respondent_tool <- tbl_usage %>% 
  inner_join(
    tbl_proficiency, by = c('respondent_id', 'tool')
  ) %>% 
  inner_join(
    tbl_increase_proficiency, by = c('respondent_id', 'tool')
  ) %>% 
  mutate(
    tool = tool %>% as_factor()
  )

rm(tbl_usage, tbl_proficiency, tbl_increase_proficiency)
```

## Suitability

```{r }
tbl_suitability <- tbl_responses %>% 
  select(respondent_id, starts_with("suited")) %>% 
  pivot_longer(cols = -respondent_id, names_to = 'tool_area', values_to = 'suitability') %>% 
  mutate(
    tool_area = str_remove(tool_area, 'suited_') %>% 
      str_replace_all("capital_modeling", "capital modeling")
  ) %>% 
  separate(tool_area, into = c("practice_area", "tool"), sep = "_") %>% 
  mutate(
    practice_area = str_to_title(practice_area)
  ) %>% 
  inner_join(
    tbl_respondent_tool, by = c('respondent_id', 'tool')
  )
```

# Techniques

```{r }
tbl_techniques <- tbl_responses %>% 
  select(respondent_id, starts_with("technique")) %>% 
  select(-techniques_other) %>% 
  pivot_longer(
    cols = starts_with('technique')
    , names_to = 'technique'
    , values_to = 'use') %>% 
  mutate(
    technique = technique %>% 
      str_remove('techniques_') %>% 
      str_replace_all("_", " ") %>% 
      str_to_title() %>% 
      str_replace('Aideep Learning', "AI/deep Learning") %>% 
      str_replace("Ladder", "ladder") %>% 
      str_replace("Models", "models") %>% 
      str_replace(" Ferg", "-Ferg") %>% 
      str_replace("Series", "series") %>% 
      str_replace("Tree Based Methods", "Tree-based methods") %>% 
      str_replace("Learning", "learning") %>% 
      str_replace("Excess Loss Analysis", "Excess loss analysis")
  )
```

# Melted barriers

```{r}
tbl_barrier <- tbl_responses %>% 
  select(respondent_id, contains("barriers")) %>% 
  select(-learning_barriers_other, -implementation_barriers_other) %>% 
  pivot_longer(
    cols = contains('barrier')
    , names_to = 'barrier'
    , values_to = 'barrier_exists') %>% 
  mutate(
    barrier_type = ifelse(
      str_starts(barrier, 'learning_')
      , 'learning'
      , 'implementation'
    )
  ) %>% 
  mutate(
    barrier = barrier %>% 
      str_remove('barriers_') %>% 
      str_remove('learning_') %>% 
      str_remove('implementation_')
  ) %>% 
  pivot_wider(
    names_from = 'barrier_type'
    , values_from = 'barrier_exists'
  ) %>% 
  inner_join(
    tbl_demographic, by = 'respondent_id'
  )
```


# Save

```{r}
rm(tbl_col_names)
```


```{r }
tbls <- ls(pattern = 'tbl_')
plts <- ls(pattern = 'plt_')
fcts <- ls(pattern = 'f_')
numbers <- ls(pattern = 'n_')
funcs <- lsf.str()
save(
  file = represtools::OutputFile(params)
  , list = c(tbls, plts, funcs, fcts, numbers)
)
```
